### PR TITLE
Create another table under graphs for graph nodes

### PR DESCRIPTION
**Pull request by TheYuanLiao**
This table contains coordinates for all the start/end nodes in graphs.car_network. For further routing using iGraph.

### CODE REVIEW

**Comment by jorgegil** [comment]
This nodes table is not really needed for routing in iGraph. When you create a graph from the edges list, it automatically creates all the nodes. But it doesn't harm to have the table of nodes, might be useful for other purposes and visualisation.

**Comment by TheYuanLiao** [comment]
The nodes and their coordinates are needed to construct a KD tree for places to find their nearest road edge node to start with.

**Comment by jorgegil** [comment]
Ah, good point! This is something that we can also pre-calculate in the database.

Something to keep in mind is the matching between node ids and node names (the database ids), i.e. a query for a route in the graph object must use the internal node ids, while the geographic origin will most likely have the original node id.

**Comment by TheYuanLiao** [comment]
Yes indeed. I paid attention to the id including the reindexing by iGraph for routing. The next step is checking the largest component.

**Pull request merged**
